### ISSUE TITLE
Latest news order

### ISSUE THREAD

**Issue by asia23** [RENCI/renci-website#229]
**At what URL is the content that needs updating?**

'https://renci-beta.netlify.app/'

**Describe why this change is necessary**

This needs updating because third position item on the News list is from 2005

**Existing Content**

Existing order of blogs, news seems to be somewhat random - not with the newest on top

**New Content**

I don't think new content is needed - but different sorting is. 

btw, consider this submission also as a testing of the github-issue driven request routine! So far, i love it! 
Thanks!

**Comment by mbwatson** [comment]
@asia23 thanks! i'll take a look and get back to you.

**Comment by mbwatson** [comment]
i'm not able to see this behavior. you see something different than what is shown in this screenshot when you land on https://renci-beta.netlify.app/?

![Screenshot from 2021-04-23 16-30-41](https://user-images.githubusercontent.com/6019870/115926703-46ad4980-a451-11eb-8748-2a8a1e7b7498.png)

there _are_ a couple articles pinned to the top (the "spotlight"ed stories), so they're out of order, but the next one after the spotlight -- for me -- is a 2021 article, as shown in the above screenshot.

**Comment by trel** [comment]
<img width="616" alt="Screen Shot 2021-04-23 at 4 38 24 PM" src="https://user-images.githubusercontent.com/55238/115927419-65f8a680-a452-11eb-85d8-a13b84ba0a49.png">

**Comment by mbwatson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RENCI website redesign and rebuild](https://trello.com/c/CI6NGFDT/12-renci-website-redesign-and-rebuild)

**Comment by mbwatson** [comment]
@trel thanks for confirming!

**Comment by asia23** [comment]
See the screen shot: just top 3 entries: 2020, 2021, 2005
***@***.***D739F8.ED43B8B0]
--
Asia Mieczkowska (she/her/hers)
***@***.******@***.***>

From: Matt Watson ***@***.***>
Reply-To: RENCI/renci-website ***@***.***>
Date: Friday, April 23, 2021 at 4:32 PM
To: RENCI/renci-website ***@***.***>
Cc: Asia Mieczkowska ***@***.***>, Mention ***@***.***>
Subject: Re: [RENCI/renci-website] Latest news order (#229)


i'm not able to see this behavior. you see something different than what is shown in this screenshot when you land on https://renci-beta.netlify.app/?

[Image removed by sender. Screenshot from 2021-04-23 16-30-41]<https://user-images.githubusercontent.com/6019870/115926703-46ad4980-a451-11eb-8748-2a8a1e7b7498.png>

**Comment by mbwatson** [comment]
@asia23 thanks for catching this Chrome.-specific issue i believe it's fixed now.
