### ISSUE TITLE
Ops teams: leads are not marked 

### ISSUE THREAD

**Issue by asia23** [RENCI/renci-website#230]
**At what URL is the content that needs updating?**

All of Operations teams

**Describe why this change is necessary**

This needs updating because teams should not be presented as leadless. Currently, they are, unlike all research teams where leads are noted. 

**Existing Content**

List of team members doesn't differentiate between member and lead. 

**New Content**

Please add: 
Finance - Kristi
ACIS - Marcin
Comms - Steph
Admins - Asia
PMO - Asia (lead), Sarah (co-lead), Marian (co-lead)

**Comment by mbwatson** [comment]
nice catch! will fix this

**Comment by mbwatson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RENCI website redesign and rebuild](https://trello.com/c/CI6NGFDT/12-renci-website-redesign-and-rebuild)
