### ISSUE TITLE
PMO members titles 

### ISSUE THREAD

**Issue by asia23** [RENCI/renci-website#232]
**At what URL is the content that needs updating?**

'https://renci-beta.netlify.app/teams/project-management'

**Describe why this change is necessary**

This needs updating because some titles are incorrect. 

**Existing Content**

Dawn Shelton: Research Project Manager
Bryttany: Research Project Manager
Marian: Research Project Coordinator
Jeremy: project manager

**New Content**

Dawn Shelton: Event Coordinator and Project Manager
Bryttany: Research Project Manager and RENCI Internship Program Manager
Marian: Senior Research Project Manager and co-lead
Jeremy: Research Project Coordinator

**Comment by mbwatson** [comment]
@asia23 thanks for the updates! this change should be rolling out shortly.
