### ISSUE TITLE
Add Access to dashboard via log in into front page somewhere

### ISSUE THREAD

**Issue by asia23** [RENCI/renci-website#236]
**Is your feature request related to a problem? Please describe.**
not a problem, but the way of connecting external and internal websites. 

**Describe the solution you'd like**
Add a button "login to Dashboard" to the external page 

**Describe alternatives you've considered**
none

**Additional context**
We are trying to promote using the Dashboard and are developing Switchboards (aka intranet) to serve RENCI community. It would be logical to include an opening to enter the internal site from external.

**Comment by mbwatson** [comment]
good thinking! we've decided to add a link in the footer.
